// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4NZdjJ4gHuzRlv2jbsT5wKeyl6HbuNk',
    appId: '1:301028908007:web:93cfa8598317f335537b42',
    messagingSenderId: '301028908007',
    projectId: 'vitu-dd103',
    authDomain: 'vitu-dd103.firebaseapp.com',
    storageBucket: 'vitu-dd103.firebasestorage.app',
    measurementId: 'G-P5N1KQXBWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2C8KbwLg7mH5Q0jx74xwFrF9f9lYdqK4',
    appId: '1:301028908007:android:d48455bf85b1968b537b42',
    messagingSenderId: '301028908007',
    projectId: 'vitu-dd103',
    storageBucket: 'vitu-dd103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncTJEej4Oj6rtCgl9i_gO2e5ASXxjgig',
    appId: '1:301028908007:ios:433af45cc873afdb537b42',
    messagingSenderId: '301028908007',
    projectId: 'vitu-dd103',
    storageBucket: 'vitu-dd103.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCncTJEej4Oj6rtCgl9i_gO2e5ASXxjgig',
    appId: '1:301028908007:ios:433af45cc873afdb537b42',
    messagingSenderId: '301028908007',
    projectId: 'vitu-dd103',
    storageBucket: 'vitu-dd103.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD4NZdjJ4gHuzRlv2jbsT5wKeyl6HbuNk',
    appId: '1:301028908007:web:1110fe011df9d89c537b42',
    messagingSenderId: '301028908007',
    projectId: 'vitu-dd103',
    authDomain: 'vitu-dd103.firebaseapp.com',
    storageBucket: 'vitu-dd103.firebasestorage.app',
    measurementId: 'G-Z0YJFBMMKC',
  );
}
